name: Build and Test

on:
  push:
    branches: [main, master, feature/*]
  pull_request:
    branches: [main, master]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.24"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Run benchmarks (short)
        run: go test -bench=. -benchmem -short ./hnsw/hnsw-extensions/hybrid/...
